CREATE DATABASE IF NOT EXISTS energy_monitor CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE energy_monitor;

CREATE TABLE IF NOT EXISTS sensor_data (
  id INT NOT NULL AUTO_INCREMENT,
  voltage FLOAT DEFAULT NULL,
  current FLOAT DEFAULT NULL,
  power FLOAT DEFAULT NULL,
  energy FLOAT DEFAULT NULL,
  frequency FLOAT DEFAULT NULL,
  pf FLOAT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS devices (
  id INT NOT NULL AUTO_INCREMENT,
  device_name VARCHAR(100) DEFAULT NULL,
  serial_number VARCHAR(100) DEFAULT NULL,
  location VARCHAR(100) DEFAULT NULL,
  ip_address VARCHAR(50) DEFAULT NULL,
  status ENUM('ONLINE','OFFLINE') DEFAULT 'OFFLINE',
  last_update DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alarm_settings (
  id INT NOT NULL AUTO_INCREMENT,
  power_limit DECIMAL(8,2) DEFAULT NULL,
  voltage_min DECIMAL(8,2) DEFAULT NULL,
  voltage_max DECIMAL(8,2) DEFAULT NULL,
  current_limit DECIMAL(8,2) DEFAULT NULL,
  pf_min DECIMAL(5,2) DEFAULT NULL,
  email_notification TINYINT(1) DEFAULT 0,
  telegram_notification TINYINT(1) DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alarm_history (
  id BIGINT NOT NULL AUTO_INCREMENT,
  device_id INT NOT NULL DEFAULT 1,
  alarm_type VARCHAR(50) NOT NULL,
  alarm_value DECIMAL(10,2) NOT NULL,
  message TEXT,
  status ENUM('ACTIVE','ACKNOWLEDGED') DEFAULT 'ACTIVE',
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acknowledged_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  level VARCHAR(20) DEFAULT NULL,
  message TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(100) DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  role ENUM('ADMIN','USER') DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO alarm_settings (id,power_limit,voltage_min,voltage_max,current_limit,pf_min) VALUES (1,4.00,180.00,240.00,10.00,0.50)
ON DUPLICATE KEY UPDATE id=id;
